# Generated on 2025-07-26 16:13:05
training:
  epochs: 5
  batch_size: 8
  gradient_accumulation: 2
  learning_rate: 3.0e-05
  optimizer: adamw
  scheduler: linear
model:
  base_model: openai/whisper-small
  language: de
  task: transcribe
  use_fp16: true
  stochastic_depth: 0.1
data:
  dataset_name: mozilla-foundation/common_voice_13_0
  subset: de
  streaming: false
  preprocessing:
    remove_background_noise: true
    max_duration: 30
logging:
  use_wandb: true
  wandb_project: whisper-german-test
  log_every_n_steps: 10
  output_dir: ./checkpoints
